### ISSUE TITLE
Panic from 'skupper-docker connection-token'

### ISSUE THREAD

**Issue by lukeyeager** [skupperproject/skupper-docker#44]
```console
$ uname -r -m -o
6.5.5-arch1-1 x86_64 GNU/Linux

$ go version
go version go1.21.1 linux/amd64

$ docker --version
Docker version 24.0.6, build ed223bc820

$ git log -n1 --pretty=oneline
97162c305b700007f360037cde1bdee16ed8507e (HEAD -> master, origin/master, origin/HEAD) Port map (#41)

$ make build-cmd
$ ./skupper-docker init 
$ ./skupper-docker status
Skupper is enabled  in interior mode'. It is not connected to any other sites. It has no exposed services.

$ docker image ls | grep skupper
quay.io/skupper/skupper-docker-controller   latest          9c987a13d24a   2 years ago    137MB
quay.io/skupper/qdrouterd                   0.4             808df108071c   2 years ago    580MB

$ ./skupper-docker connection-token ./my.token
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x46a2ff]
...
```
Full output: [skupper-docker-panic.txt](https://github.com/skupperproject/skupper-docker/files/12807955/skupper-docker-panic.txt)

Looks like it's failing to encode the secret cert data. Perhaps some important updates have gone into `github.com/skupperproject/skupper/blob/main/pkg/certs` since this repo's go.mod was updated?

I was hoping to use this to create a link between docker networks on multiple hosts. Is there a more up-to-date project I should be using to do that?

**Comment by ted-ross** [comment]
Hi Luke,

Skupper-docker is quite old and has been replaced by the --platform option
in the main skupper CLI.  Skupper-docker should probably be removed or
otherwise deprecated as it hasn't been updated in a couple of years.

The --platform option allows a full Skupper site to be initialized in
'kubernetes' as has always been supported, or in 'podman' for operation on
a bare-metal/VM container platform.  There is not yet platform support for
Docker.

At present there isn't a solution for Docker to Docker (direct).  However,
you could go Docker - Kubernetes - Docker using the 'skupper gateway'
commands.  This is described here:
https://skupper.io/docs/cli/index.html#exposing-services-ns.

Let us know if you need more information.

-Ted

**Comment by lukeyeager** [comment]
Ok, thanks for the quick response! I'll check out the 'gateway' command.
